### ISSUE TITLE
readme/help window partly outside of screen bottom if 700 pixel height resolution

### ISSUE THREAD

**Issue by GitHubRulesOK** [nod5/HighlightJump#1]
@nod5 
Thanks for all the hard work updating to the latest releases, I have difficulty with a number of the new features but will raise each one as a separate issue to be addressed and closed.

My first suggestion is the **read me** "help screen" which is useful for early users to keep active whilst experimenting. The main problem I have is the height on a laptop screen.
At the top I can see a lot of the start up info and version (which I now don't need as it is running) but I cannot see the more advanced features (after mouse shortcuts) as they go "off-screen"

I could edit my copy easily to a shorter heading but suggest for other with 700-800 high screens the **start up / help about / it does not work FAQ** info could be a separate  "page" to the **running help which could be assigned to F1 since SumatraPDF does not use that key**

**Comment by nod5** [comment]
Thanks for feedback. Will fix, one way or another. Alternatives I'm considering:
1. Put help text in a scrolling window.
2. Revert to only show readme.md in Notepad.
3. Revert to only open the GitHub readme page.

**Comment by GitHubRulesOK** [comment]
1) pretty but overkill and scrolling may detract from simplicity of a static side window
2) keep info: as "Usage" without the setup lines
so version could be higher in title and relocate 
> 
>   SETUP:
>   1. Get SumatraPDF Prerelease version
>      https://www.sumatrapdfreader.org/prerelease.html
> 

>   2. In SumatraPDF 
>     Settings > Advanced Options > SaveIntoDocument = false
>     Settings > Advanced Options > FullPathInTitle = true
> 
>
>  3. Install AutoHotkey unicode, https://www.autohotkey.com

into a **readme first** with trouble shooting tips

3) for portable use avoid calling GitHub for help



E.G. something like this where I the OK button is not needed since I can use top right X

![image](https://user-images.githubusercontent.com/12754913/74390879-6a5f1380-4dfa-11ea-9993-21a04ef021e2.png)

**Comment by nod5** [comment]
On second thought I will probably for simplicity just do
4. Keep mostly just the shortcuts info and reference to github/readme for more ( < 600 px height)

**Comment by nod5** [comment]
Fixed in release 2020-02-18, bb9ea5e
Now shows smaller window with only shortcuts information.
A separate tray menu action shows local file readme.html (based on README.md) in default browser.

**Comment by GitHubRulesOK** [comment]
Great improvement and leaves room for many other enhancements 🙂
